name: Acesso remoto com AnyDesk

on: workflow_dispatch

jobs:
  remote_access:
    runs-on: ubuntu-latest

    steps:
      - name: Instalar pacotes necessários
        run: |
          sudo apt-get update
          sudo apt-get install -y ca-certificates curl apt-transport-https

      - name: Adicionar chave GPG do AnyDesk
        run: |
          sudo install -m 0755 -d /etc/apt/keyrings
          sudo curl -fsSL https://keys.anydesk.com/repos/DEB-GPG-KEY -o /etc/apt/keyrings/keys.anydesk.com.asc
          sudo chmod a+r /etc/apt/keyrings/keys.anydesk.com.asc

      - name: Adicionar repositório do AnyDesk
        run: |
          echo "deb [signed-by=/etc/apt/keyrings/keys.anydesk.com.asc] https://deb.anydesk.com all main" | sudo tee /etc/apt/sources.list.d/anydesk-stable.list > /dev/null
          
      - name: Atualizar repositórios e instalar AnyDesk
        run: |
          sudo apt-get update
          sudo apt-get install -y anydesk

      - name: Iniciar AnyDesk em segundo plano
        run: |
          anydesk &
          sleep 5  # Espera o AnyDesk iniciar

      - name: Configurar e iniciar Xvfb
        run: |
          export DISPLAY=:99
          nohup Xvfb :99 -screen 0 1024x768x16 &

      - name: Espera o AnyDesk estar rodando
        run: |
          sleep 30  # Tempo para o AnyDesk iniciar

      - name: Mostrar informações de acesso
        run: |
          echo "Você pode acessar o AnyDesk no ID: $(anydesk --get-id)"
