name: VPS com Zrok

on: workflow_dispatch

jobs:
  zrok_job:
    runs-on: ubuntu-latest
    steps:
      - name: Baixar e instalar o Zrok
        run: |
          # Baixar a versão mais recente do Zrok
          curl -L https://github.com/openziti/zrok/releases/download/v0.4.49/zrok_0.4.49_linux_amd64.tar.gz -o zrok.tar.gz

          # Descompactar
          tar -xzvf zrok.tar.gz

          # Mover o binário para /usr/local/bin para fácil acesso
          sudo mv zrok /usr/local/bin/

      - name: Habilitar túnel com Zrok
        run: |
          # Ativar o Zrok com o comando enable (sem precisar de auth)
          zrok enable ${{secrets.ZROK_AUTH}}

      - name: Configurar SSH (exemplo)
        run: |
          sudo apt-get update
          sudo apt-get install -y openssh-server
          sudo systemctl start ssh

      - name: Iniciar o Zrok para criar o túnel
        run: |
          # Criar um túnel SSH (ou qualquer outro serviço que você queira expor)
          zrok share public 22
          
          # Dormir por um tempo para manter o túnel ativo (ex: 1 hora)
          sleep 3600
