name: VPS Gambiarra

on: workflow_dispatch

jobs:
  vps_job:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Ngrok
        run: |
          sudo apt-get update
          sudo apt-get install -y openssh-server
          sudo systemctl start ssh
          curl -s https://ngrok-agent.s3.amazonaws.com/ngrok.asc | sudo tee /etc/apt/keyrings/ngrok.asc >/dev/null
          echo "deb [signed-by=/etc/apt/keyrings/ngrok.asc] https://ngrok-agent.s3.amazonaws.com buster main" | sudo tee /etc/apt/sources.list.d/ngrok.list
          sudo apt-get update
          sudo apt-get install ngrok
          ngrok config add-authtoken ${{ secrets.NGROK_AUTH_TOKEN }}
          ngrok tcp 22 > ngrok.log &
          sleep 5
          cat ngrok.log
      - name: Keep Alive
        run: sleep 3600  # 1 hora "vps" rodando
