name: Testar RustDesk no GitHub Actions

on: workflow_dispatch

jobs:
  rustdesk_job:
    runs-on: ubuntu-latest

    steps:
      - name: Atualizar pacotes
        run: |
          sudo apt-get update
          sudo apt-get install -y wget xvfb

      - name: Baixar e instalar RustDesk
        run: |
          # Baixar o pacote .deb do RustDesk
          wget https://github.com/rustdesk/rustdesk/releases/download/nightly/rustdesk-1.3.9-x86_64.deb
          
          # Instalar o pacote .deb
          sudo dpkg -i rustdesk-1.3.9-x86_64.deb
          sudo apt-get install -f  # Resolver dependências

      - name: Configurar e iniciar Xvfb (servidor gráfico virtual)
        run: |
          export DISPLAY=:99
          nohup Xvfb :99 -screen 0 1024x768x16 &

      - name: Iniciar RustDesk
        run: |
          # Rodar RustDesk em segundo plano
          nohup rustdesk &

      - name: Esperar RustDesk iniciar
        run: |
          sleep 30  # Espera o RustDesk iniciar

      - name: Mostrar informações de acesso
        run: |
          # Avisa o ID do RustDesk (o número que você vai usar para se conectar)
          echo "Você pode acessar o RustDesk no ID: $(ps aux | grep rustdesk | awk '{print $2}')"
