name: Acesso remoto com RustDesk

on: workflow_dispatch

jobs:
  remote_access:
    runs-on: ubuntu-latest

    steps:
      - name: Instalar pacotes necessários
        run: |
          sudo apt-get update
          sudo apt-get install -y xvfb wget

      - name: Baixar e instalar RustDesk
        run: |
          # Baixar a versão mais recente do RustDesk para Linux
          wget https://github.com/rustdesk/rustdesk/releases/download/v1.1.9/rustdesk-1.1.9-linux-x86_64.tar.gz
          tar -xvzf rustdesk-1.1.9-linux-x86_64.tar.gz
          cd rustdesk-1.1.9-linux-x86_64

      - name: Configurar Xvfb para criar um ambiente gráfico
        run: |
          export DISPLAY=:99
          nohup Xvfb :99 -screen 0 1024x768x16 &

      - name: Rodar RustDesk em segundo plano
        run: |
          ./rustdesk &

      - name: Espera o RustDesk estar rodando
        run: |
          sleep 30  # Tempo para o RustDesk iniciar

      - name: Mostrar informações de acesso
        run: |
          # Aqui você pode colocar um comando para obter o ID ou a URL do RustDesk (caso necessário)
          echo "Você pode acessar o RustDesk na máquina com a interface gráfica"
